__XX_TEMPLATE_COMPOENTS_OVERLOADS(float, rcp)
__XX_TEMPLATE_COMPOENTS_OVERLOADS(float, radians)
__XX_TEMPLATE_COMPOENTS_OVERLOADS(float, saturate)
__XX_TEMPLATE_COMPOENTS_OVERLOADS(float, noise)

__XX_TEMPLATE_COMPOENTS_OVERLOADS(int, abs)
__XX_TEMPLATE_BINARY_COMPOENTS_OVERLOADS(int, min)
__XX_TEMPLATE_BINARY_COMPOENTS_OVERLOADS(int, max)
__XX_TEMPLATE_BINARY_COMPOENTS_OVERLOADS(uint, min)
__XX_TEMPLATE_BINARY_COMPOENTS_OVERLOADS(uint, max)

